# Generated by Django 6.0 on 2025-12-14 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowings', '0003_alter_borrowing_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10)),
                ('type', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=10)),
                ('session_url', models.URLField()),
                ('session_id', models.CharField(max_length=255)),
                ('money_to_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='borrowings.borrowing')),
            ],
        ),
    ]
