# Generated by Django 6.0 on 2025-12-14 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0003_alter_borrowing_user'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='borrowing',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='payments',
                to='borrowings.borrowing'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(
                choices=[
                    ('Payment',
                     'Payment'),
                    ('Fine',
                     'Fine')],
                max_length=10),
        ),
    ]
