# Generated by Django 6.0 on 2025-12-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('borrow_date',
                 models.DateField(
                     auto_now_add=True)),
                ('expected_return_date',
                 models.DateField()),
                ('actual_return_date',
                 models.DateField(
                     default='0000-00-00')),
                ('user',
                 models.CharField(
                     default='Test',
                     max_length=100)),
                ('book',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='books.book')),
            ],
        ),
    ]
