# Generated by Django 6.0 on 2025-12-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_borrowing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrowing',
        ),
    ]
