# Generated by Django 6.0 on 2025-12-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
