# Generated by Django 5.2.9 on 2025-12-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0004_alter_borrowing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='id',
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID'),
        ),
    ]
